_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 1
                - 2
                - 16
                - 55
            "4": 3.12.11
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
agent:
    value:
        batch_size: 64
        buffer_capacity: 50000
        gamma: 0.99
        hidden_size: 20
        lr: 0.001
        min_replay: 1000
        name: DQN
        target_sync: 200
env:
    value:
        height: 6
        max_steps: 50
        render_cell_size: 32
        walls:
            - - 1
              - 1
            - - 2
              - 1
            - - 3
              - 1
            - - 3
              - 2
            - - 3
              - 3
        width: 6
train:
    value:
        episodes: 500
        eps_decay: 0.995
        eps_end: 0.05
        eps_start: 1
        eval_interval: 1000
        max_steps: 200
        render: false
        seed: 10
wandb:
    value:
        enabled: true
        entity: conehed
        group: rlcone
        project: meta_BTSP_RL
